"""Create table user

Revision ID: 19f54b938643
Revises: 59d565e13102
Create Date: 2022-07-16 00:44:39.608628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f54b938643'
down_revision = '59d565e13102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
